// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanupOldLogs removes old log entries based on retention policy
 */
export function CleanupOldLogs(): $CancellablePromise<void> {
    return $Call.ByID(810309503);
}

/**
 * ClearLogs removes all log entries (use with caution)
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2278642273);
}

/**
 * GetLogConfig returns the current logging configuration
 */
export function GetLogConfig(): $CancellablePromise<$models.LogConfig> {
    return $Call.ByID(123486997).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLogEntries retrieves log entries with filtering and pagination
 */
export function GetLogEntries(filter: $models.LogFilter): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(173630445, filter).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLogEntriesCount returns the total count of log entries
 */
export function GetLogEntriesCount(filter: $models.LogFilter): $CancellablePromise<number> {
    return $Call.ByID(2698059692, filter);
}

/**
 * GetLogLevels returns available log levels
 */
export function GetLogLevels(): $CancellablePromise<string[]> {
    return $Call.ByID(897162204).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLogModules returns available log modules
 */
export function GetLogModules(): $CancellablePromise<string[]> {
    return $Call.ByID(1436279904).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLogStats returns statistics about log entries
 */
export function GetLogStats(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(2363908826).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetLogsByDateRange returns log entries within a date range
 */
export function GetLogsByDateRange(startTime: time$0.Time, endTime: time$0.Time, limit: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(1815696978, startTime, endTime, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLogsByLevel returns log entries for a specific level
 */
export function GetLogsByLevel(level: string, limit: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(1882376481, level, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLogsByModule returns log entries for a specific module
 */
export function GetLogsByModule($module: string, limit: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(3482482801, $module, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRecentLogs returns the most recent log entries (last 100)
 */
export function GetRecentLogs(): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(3823796623).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SearchLogs searches log entries by message content
 */
export function SearchLogs(searchText: string, limit: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(232367186, searchText, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(3900412202);
}

/**
 * UpdateLogConfig updates the logging configuration
 */
export function UpdateLogConfig(config: $models.LogConfig): $CancellablePromise<void> {
    return $Call.ByID(2454674592, config);
}

// Private type creation functions
const $$createType0 = $models.LogConfig.createFrom;
const $$createType1 = $models.LogEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
