// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * LogConfig represents logging configuration
 */
export class LogConfig {
    "enabled": boolean;
    "log_level": LogLevel;
    "log_modules": LogModule[];
    "log_new_items": boolean;
    "log_api_requests": boolean;
    "log_websocket": boolean;
    "retention_days": number;
    "max_entries": number;
    "real_time_updates": boolean;

    /** Creates a new LogConfig instance. */
    constructor($$source: Partial<LogConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("log_level" in $$source)) {
            this["log_level"] = LogLevel.$zero;
        }
        if (!("log_modules" in $$source)) {
            this["log_modules"] = [];
        }
        if (!("log_new_items" in $$source)) {
            this["log_new_items"] = false;
        }
        if (!("log_api_requests" in $$source)) {
            this["log_api_requests"] = false;
        }
        if (!("log_websocket" in $$source)) {
            this["log_websocket"] = false;
        }
        if (!("retention_days" in $$source)) {
            this["retention_days"] = 0;
        }
        if (!("max_entries" in $$source)) {
            this["max_entries"] = 0;
        }
        if (!("real_time_updates" in $$source)) {
            this["real_time_updates"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LogConfig {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log_modules" in $$parsedSource) {
            $$parsedSource["log_modules"] = $$createField2_0($$parsedSource["log_modules"]);
        }
        return new LogConfig($$parsedSource as Partial<LogConfig>);
    }
}

/**
 * LogEntry represents a single log entry
 */
export class LogEntry {
    "id": number;
    "timestamp": time$0.Time;
    "module": LogModule;
    "level": LogLevel;
    "message": string;

    /**
     * JSON string for flexible data
     */
    "metadata": string;
    "created_at": time$0.Time;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("module" in $$source)) {
            this["module"] = LogModule.$zero;
        }
        if (!("level" in $$source)) {
            this["level"] = LogLevel.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * LogFilter represents filters for querying logs
 */
export class LogFilter {
    "module"?: LogModule | null;
    "level"?: LogLevel | null;
    "start_time"?: time$0.Time | null;
    "end_time"?: time$0.Time | null;

    /**
     * Search in message
     */
    "search"?: string;
    "limit"?: number;
    "offset"?: number;

    /** Creates a new LogFilter instance. */
    constructor($$source: Partial<LogFilter> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFilter($$parsedSource as Partial<LogFilter>);
    }
}

/**
 * LogLevel represents the severity of the log entry
 */
export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLevelDebug = "debug",
    LogLevelInfo = "info",
    LogLevelWarning = "warning",
    LogLevelError = "error",
    LogLevelSuccess = "success",
};

/**
 * LogModule represents which part of the application generated the log
 */
export enum LogModule {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogModuleLiveSearch = "livesearch",
    LogModuleSettings = "settings",
    LogModuleWebSocket = "websocket",
    LogModuleAPI = "api",
    LogModuleSystem = "system",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
