// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<models.Config>;

export function SaveConfig(arg1:models.Config):Promise<void>;
