// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {livesearch} from '../models';

export function AddTradeLink(arg1:string,arg2:string):Promise<void>;

export function ListTradeLinks():Promise<Array<livesearch.TradeLink>>;

export function StartLiveSearch():Promise<Array<livesearch.TradeLink>>;

export function UpdateTradeLinks(arg1:Array<livesearch.TradeLink>):Promise<void>;
