// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTradeLink(arg1, arg2) {
  return window['go']['livesearch']['Handler']['AddTradeLink'](arg1, arg2);
}

export function ListTradeLinks() {
  return window['go']['livesearch']['Handler']['ListTradeLinks']();
}

export function UpdateTradeLinks(arg1) {
  return window['go']['livesearch']['Handler']['UpdateTradeLinks'](arg1);
}
