// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {livesearch} from '../models';
import {context} from '../models';

export function AddTradeLink(arg1:string,arg2:string):Promise<void>;

export function ListTradeLinks():Promise<Array<livesearch.TradeLink>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartLiveSearch():Promise<Array<livesearch.TradeLink>>;

export function StopLiveSearch():Promise<void>;

export function UpdateTradeLinks(arg1:Array<livesearch.TradeLink>):Promise<void>;
