// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {livesearch} from '../models';
import {context} from '../models';

export function AddTradeLink(arg1:string,arg2:string):Promise<void>;

export function GetGoToHideout():Promise<boolean>;

export function ListTradeLinks():Promise<Array<livesearch.TradeLinkDTO>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetGoToHideout(arg1:boolean):Promise<void>;

export function StartLiveSearch():Promise<Array<livesearch.TradeLink>>;

export function StopLiveSearch():Promise<void>;

export function UpdateTradeLink(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;
