// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTradeLink(arg1, arg2) {
  return window['go']['livesearch']['Handler']['AddTradeLink'](arg1, arg2);
}

export function GetGoToHideout() {
  return window['go']['livesearch']['Handler']['GetGoToHideout']();
}

export function ListTradeLinks() {
  return window['go']['livesearch']['Handler']['ListTradeLinks']();
}

export function SetContext(arg1) {
  return window['go']['livesearch']['Handler']['SetContext'](arg1);
}

export function SetGoToHideout(arg1) {
  return window['go']['livesearch']['Handler']['SetGoToHideout'](arg1);
}

export function StartLiveSearch() {
  return window['go']['livesearch']['Handler']['StartLiveSearch']();
}

export function StopLiveSearch() {
  return window['go']['livesearch']['Handler']['StopLiveSearch']();
}

export function UpdateTradeLink(arg1, arg2, arg3, arg4) {
  return window['go']['livesearch']['Handler']['UpdateTradeLink'](arg1, arg2, arg3, arg4);
}
