// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupOldLogs() {
  return window['go']['logging']['Handler']['CleanupOldLogs']();
}

export function ClearLogs() {
  return window['go']['logging']['Handler']['ClearLogs']();
}

export function GetLogConfig() {
  return window['go']['logging']['Handler']['GetLogConfig']();
}

export function GetLogEntries(arg1) {
  return window['go']['logging']['Handler']['GetLogEntries'](arg1);
}

export function GetLogEntriesCount(arg1) {
  return window['go']['logging']['Handler']['GetLogEntriesCount'](arg1);
}

export function GetLogLevels() {
  return window['go']['logging']['Handler']['GetLogLevels']();
}

export function GetLogModules() {
  return window['go']['logging']['Handler']['GetLogModules']();
}

export function GetLogStats() {
  return window['go']['logging']['Handler']['GetLogStats']();
}

export function GetLogsByDateRange(arg1, arg2, arg3) {
  return window['go']['logging']['Handler']['GetLogsByDateRange'](arg1, arg2, arg3);
}

export function GetLogsByLevel(arg1, arg2) {
  return window['go']['logging']['Handler']['GetLogsByLevel'](arg1, arg2);
}

export function GetLogsByModule(arg1, arg2) {
  return window['go']['logging']['Handler']['GetLogsByModule'](arg1, arg2);
}

export function GetRecentLogs() {
  return window['go']['logging']['Handler']['GetRecentLogs']();
}

export function SearchLogs(arg1, arg2) {
  return window['go']['logging']['Handler']['SearchLogs'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['logging']['Handler']['SetContext'](arg1);
}

export function UpdateLogConfig(arg1) {
  return window['go']['logging']['Handler']['UpdateLogConfig'](arg1);
}
