// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logging} from '../models';
import {time} from '../models';
import {context} from '../models';

export function CleanupOldLogs():Promise<void>;

export function ClearLogs():Promise<void>;

export function GetLogConfig():Promise<logging.LogConfig>;

export function GetLogEntries(arg1:logging.LogFilter):Promise<Array<logging.LogEntry>>;

export function GetLogEntriesCount(arg1:logging.LogFilter):Promise<number>;

export function GetLogLevels():Promise<Array<string>>;

export function GetLogModules():Promise<Array<string>>;

export function GetLogStats():Promise<Record<string, any>>;

export function GetLogsByDateRange(arg1:time.Time,arg2:time.Time,arg3:number):Promise<Array<logging.LogEntry>>;

export function GetLogsByLevel(arg1:string,arg2:number):Promise<Array<logging.LogEntry>>;

export function GetLogsByModule(arg1:string,arg2:number):Promise<Array<logging.LogEntry>>;

export function GetRecentLogs():Promise<Array<logging.LogEntry>>;

export function SearchLogs(arg1:string,arg2:number):Promise<Array<logging.LogEntry>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateLogConfig(arg1:logging.LogConfig):Promise<void>;
