// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * MIGRADO: Usar servicio de aplicación (mantener compatibilidad con frontend)
 */
export function AddTradeLink(url: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(3596612099, url, description);
}

/**
 * MIGRADO: Usar servicio de aplicación
 */
export function DeleteTradeLink(id: number): $CancellablePromise<void> {
    return $Call.ByID(2544351275, id);
}

/**
 * GetAllLinkStatuses retorna los estados actuales usando Clean Architecture
 */
export function GetAllLinkStatuses(): $CancellablePromise<{ [_: `${number}`]: string }> {
    return $Call.ByID(1096111801).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * MIGRADO: Usar servicio de aplicación
 */
export function GetGoToHideout(): $CancellablePromise<boolean> {
    return $Call.ByID(3389697673);
}

/**
 * MIGRADO: Usar servicio de aplicación
 */
export function GetHideoutQueueSize(): $CancellablePromise<number> {
    return $Call.ByID(1736301070);
}

/**
 * MIGRADO: Usar servicio de aplicación
 */
export function IsHideoutProcessing(): $CancellablePromise<boolean> {
    return $Call.ByID(2435293671);
}

/**
 * IsLiveSearchRunning verifica si la búsqueda está corriendo usando Clean Architecture
 */
export function IsLiveSearchRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(940322137);
}

/**
 * MIGRADO: Usar servicio de aplicación (mantener compatibilidad con frontend)
 */
export function ListTradeLinks(): $CancellablePromise<$models.TradeLink[]> {
    return $Call.ByID(2751393423).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenLogsWindow(): $CancellablePromise<void> {
    return $Call.ByID(2916030603);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(472825787);
}

/**
 * MIGRADO: Usar servicio de aplicación
 */
export function SetGoToHideout(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3798349037, enabled);
}

/**
 * StartLiveSearch inicia la búsqueda en vivo usando Clean Architecture
 */
export function StartLiveSearch(): $CancellablePromise<$models.TradeLink[]> {
    return $Call.ByID(3906018782).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * StopLiveSearch detiene la búsqueda en vivo usando Clean Architecture
 */
export function StopLiveSearch(): $CancellablePromise<void> {
    return $Call.ByID(3475946234);
}

export function TestLogEvent(): $CancellablePromise<void> {
    return $Call.ByID(3249663834);
}

/**
 * MIGRADO: Usar servicio de aplicación
 */
export function UpdateTradeLink(id: number, url: string, description: string, selected: boolean): $CancellablePromise<void> {
    return $Call.ByID(1021348257, id, url, description, selected);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
