// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function LoadConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(4270080255).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveConfig(cfg: $models.Config | null): $CancellablePromise<void> {
    return $Call.ByID(2019787458, cfg);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
