// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "poesessid": string;
    "accountName": string;
    "league": string;
    "automationEnabled": boolean;
    "delay": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("poesessid" in $$source)) {
            this["poesessid"] = "";
        }
        if (!("accountName" in $$source)) {
            this["accountName"] = "";
        }
        if (!("league" in $$source)) {
            this["league"] = "";
        }
        if (!("automationEnabled" in $$source)) {
            this["automationEnabled"] = false;
        }
        if (!("delay" in $$source)) {
            this["delay"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
