// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function LoadConfig():Promise<settings.Config>;

export function SaveConfig(arg1:settings.Config):Promise<void>;
