// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig() {
  return window['go']['settings']['Handler']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['settings']['Handler']['SaveConfig'](arg1);
}
